Fixed crasher for duplicated RRULE
The ICS in the example was generated either by Fastmail or Thunderbird, or an
interaction of the two, and causes a crasher like:

  File ".../site-packages/recurring_ical_events.py", line 189, in __init__
    self.rrule = self.create_rule_with_start(_rule.to_ical().decode())
AttributeError: 'list' object has no attribute 'to_ical'